services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      # Configuração padrão para o ambiente principal
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/springbootmvc
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      # Defina o perfil ativo como necessário (ex: 'test' para rodar com db-test)
      SPRING_PROFILES_ACTIVE: test
    depends_on:
      - db
      - db-test

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: springbootmvc
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-test:
    image: postgres:latest
    container_name: db-test
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db

volumes:
  postgres_data:
